### ISSUE TITLE
如何保存历史的Issues

### ISSUE THREAD

**Issue by mixool** [phusl/goproxy#1907]
这么多有料的东西，关了Issues后是不是没得看了啊？

**Comment by phuslu** [comment]
我会导出的。

**Comment by mixool** [comment]
@phuslu `curl -L git.io/get-goproxy-vps | bash`  
命令会受到影响么，每次reinstall完vps我都要执行的。。。

**Comment by phuslu** [comment]
啊，这个会。改成这个吧
```
curl -L git.io/get-goproxy-vps.sh
```

**Comment by panpeach** [comment]
关闭Issues非常可惜，导出的Issues，希望有人接手转战到其他地方继续讨论。
再有goproxy自动更新希望有效。

**Comment by sundaqing1969** [comment]
导出的讨论在什么地方下载？

**Comment by Kisesy** [comment]
凛冬将至啊

**Comment by pgz123** [comment]
又关？

**Comment by lizongzeshunshun** [comment]
随手写了个脚本。正在爬

**Comment by lizongzeshunshun** [comment]
[gp_issues.zip](https://github.com/phuslu/goproxy/files/1159185/gp_issues.zip)

可能稍微有几个issues遗漏（因为请求数太多）。

最后感谢@phuslu这么长时间以来的贡献，谢谢。

**Comment by MeABc** [comment]
还是社长导出完整一点。。。。

**Comment by phuslu** [comment]
汗，我本来打算用 https://github.com/gizur/github-issues-export 这个到处的，还没搞定。安装总报错。

**Comment by redapple0204** [comment]
@phuslu 这都四五年前的脚本了

**Comment by panpeach** [comment]
@lizongzeshunshun 
导出的1910个.html，查看起来有点不方便，最好弄个标题目录，查找起来才方便啊

**Comment by pgz123** [comment]
感谢@phuslu这么长时间以来的贡献，谢谢。

**Comment by hg123** [comment]
谢谢社长

**Comment by redapple0204** [comment]
@panpeach 我替他回复下，获取标题很麻烦，用软件获取不是不行，但是会把整个项目全部爬下来，太大了。
